INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (1, '第1章 JavaScript初探', NULL, NULL, 1101, 1);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (2, '第2章JavaScript语言基础', NULL, NULL, 1101, 2);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (3, '第3章 常用内置对象', NULL, NULL, 1101, 3);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (4, '第4章自定义对象及表格操作', NULL, NULL, 1101, 4);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (5, '第5章 BOM和DOM', NULL, NULL, 1101, 5);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (6, '第6章 项目实战', NULL, NULL, 1101, 6);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (7, '第7章 jQuery基础', NULL, NULL, 1101, 7);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (8, '第8章 jQuery进阶', NULL, NULL, 1101, 8);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (9, '第9章 项目实战：jQuery UI实现服饰网站、MUI移动布局、Bootstrap响应式布局', NULL, NULL, 1101, 9);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (10, '第一章 Java概述', NULL, NULL, 1108, 1);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (11, '第二章 Java环境搭建和程序初体验', NULL, NULL, 1108, 2);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (12, '第三章 Java类基础知识', NULL, NULL, 1108, 3);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (13, '第四章 面向对象和类', NULL, NULL, 1108, 4);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (14, '第五章 继承、接口和抽象类', NULL, NULL, 1108, 5);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (15, '第六章 static、final和常量设计', NULL, NULL, 1108, 6);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (16, '第七章 package、import和classpath', NULL, NULL, 1108, 7);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (17, '第八章 Java常用类', NULL, NULL, 1108, 8);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (18, '第九章 Java异常和异常处理', NULL, NULL, 1108, 9);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (19, '第十章 Java数据结构', NULL, NULL, 1108, 10);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (20, '第十一章 Java文件读写', NULL, NULL, 1108, 11);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (21, '第十二章 Java案例实践和总结', NULL, NULL, 1108, 12);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (22, '开发工具简介', NULL, NULL, 1104, 1);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (23, 'HTML基础', NULL, NULL, 1104, 2);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (24, 'CSS基础', NULL, NULL, 1104, 3);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (25, 'HTML5', NULL, NULL, 1104, 4);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (26, 'CSS3 高级选择器与常用属性', NULL, NULL, 1104, 5);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (27, 'CSS3 转换、过渡与动画', NULL, NULL, 1104, 6);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (28, 'CSS3 布局与移动端适应', NULL, NULL, 1104, 7);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (29, 'vue 框架入门', NULL, NULL, 1104, 8);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (30, '222', NULL, NULL, 1101, NULL);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (31, '123214', NULL, NULL, 1101, NULL);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (33, '222222', NULL, NULL, 1101, NULL);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (34, '4444444', NULL, NULL, 1101, NULL);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (36, '12344', NULL, NULL, 1101, NULL);
INSERT INTO `cysx_chapter` (`chapter_id`, `chapter_name`, `time`, `video_path`, `course_id`, `order_id`) VALUES (37, '777', NULL, NULL, 1109, 1);
